def chip_types_dict():
    return {'ChipTypeMap': {'MPC 3D 16x 10GE': {'PFEs': 4,
                                                'center_chip': {'mq': 1},
                                                'lookup_chip': {'lu': 1}},
                            'MPC Type 1 3D': {'PFEs': 1,
                                              'center_chip': {'mq': 1},
                                              'lookup_chip': {'lu': 1}},
                            'MPC2E NG HQoS': {'PFEs': 1,
                                              'center_chip': {'xm': 1},
                                              'lookup_chip': {'xl': 1}},
                            'MPC4E 3D 32XGE': {'PFEs': 2,
                                               'center_chip': {'xm': 1},
                                               'lookup_chip': {'lu': 2}},
                            'MPCE Type 1 3D': {'PFEs': 1,
                                               'center_chip': {'mq': 1},
                                               'lookup_chip': {'lu': 1}},
                            'MS-MPC': {'PFEs': 1,
                                       'center_chip': {'xm': 1},
                                       'lookup_chip': {'lu': 1}},
                            'MPC Type 2 3D': {'PFEs': 2,
                                              'center_chip': {
                                                  'mq': 2},
                                              'lookup_chip': {
                                                  'lu': 2}},
                            'MPC Type 2 3D Q': {'PFEs': 2,
                                                'center_chip': {'mq':2},
                                                'lookup_chip': {'lu':2}},
                            'MPC Type 2 3D EQ': {'PFEs': 2,
                                                 'center_chip': {'mq': 2},
                                                 'lookup_chip': {'lu': 2}},
                            'MPCE Type 3 3D': {'PFEs': 1,
                                               'center_chip': {'xm': 1},
                                               'lookup_chip': {'lu': 4}},
                            'MPC5E 3D 24XGE+6XLGE': {'PFEs':1,
                                                  'center_chip':{'xm':2},
                                                  'lookup_chip': {'xl':1}},
                            'MPC7E 3D MRATE-12xQSFPP-XGE-XLGE-CGE': {'PFEs':2,
                                                    'center_chip':{'mqss':2},
                                                    'lookup_chip': {'luss':2}},
                            'MPC6E 3D': {'PFEs':2,
                                                    'center_chip':{'xm':4},
                                                    'lookup_chip': {'xl':2}},
                            'MPC8E 3D': {'PFEs':4,
                                                    'center_chip':{'mqss':4},
                                                    'lookup_chip': {'luss':4}},
                            'MPC9E 3D': {'PFEs':4,
                                                    'center_chip':{'mqss':4},
                                                    'lookup_chip': {'luss':4}},
                            'MPC4E 3D 32XGE': {'PFEs':2,
                                                    'center_chip':{'xm':2},
                                                    'lookup_chip': {'lu':4}},
                            'MPC4E 3D 32XGE': {'PFEs':2,
                                                    'center_chip':{'xm':2},
                                                    'lookup_chip': {'lu':4}},
                            'MPC7E 3D 40XGE': {'PFEs':2,
                                                    'center_chip':{'mqss':2},
                                                    'lookup_chip': {'luss':2}},
                            'MPC5E 3D Q 2CGE+4XGE': {'PFEs':2,
                                                    'center_chip':{'xm':2},
                                                    'lookup_chip': {'xl':1}}
                           }}
